// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasThere.Api.Data;

#nullable disable

namespace WasThere.Api.Migrations
{
    [DbContext(typeof(ClubEventContext))]
    [Migration("20260111000000_AddAuth0UserIdToUser")]
    partial class AddAuth0UserIdToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasThere.Api.Models.Act", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("WasThere.Api.Models.ClubNight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("FlyerId")
                        .HasColumnType("integer");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("FlyerId");

                    b.HasIndex("VenueId");

                    b.ToTable("ClubNights");
                });

            modelBuilder.Entity("WasThere.Api.Models.ClubNightAct", b =>
                {
                    b.Property<int>("ClubNightId")
                        .HasColumnType("integer");

                    b.Property<int>("ActId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLiveSet")
                        .HasColumnType("boolean");

                    b.HasKey("ClubNightId", "ActId");

                    b.HasIndex("ActId");

                    b.ToTable("ClubNightActs");
                });

            modelBuilder.Entity("WasThere.Api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WasThere.Api.Models.Flyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Flyers");
                });

            modelBuilder.Entity("WasThere.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0UserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WasThere.Api.Models.UserClubNightAttendance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ClubNightId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ClubNightId");

                    b.HasIndex("ClubNightId");

                    b.ToTable("UserClubNightAttendances");
                });

            modelBuilder.Entity("WasThere.Api.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("WasThere.Api.Models.ClubNight", b =>
                {
                    b.HasOne("WasThere.Api.Models.Event", "Event")
                        .WithMany("ClubNights")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasThere.Api.Models.Flyer", "Flyer")
                        .WithMany("ClubNights")
                        .HasForeignKey("FlyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WasThere.Api.Models.Venue", "Venue")
                        .WithMany("ClubNights")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Flyer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WasThere.Api.Models.ClubNightAct", b =>
                {
                    b.HasOne("WasThere.Api.Models.Act", "Act")
                        .WithMany("ClubNightActs")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasThere.Api.Models.ClubNight", "ClubNight")
                        .WithMany("ClubNightActs")
                        .HasForeignKey("ClubNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("ClubNight");
                });

            modelBuilder.Entity("WasThere.Api.Models.Flyer", b =>
                {
                    b.HasOne("WasThere.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasThere.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WasThere.Api.Models.UserClubNightAttendance", b =>
                {
                    b.HasOne("WasThere.Api.Models.ClubNight", "ClubNight")
                        .WithMany("Attendances")
                        .HasForeignKey("ClubNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasThere.Api.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubNight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasThere.Api.Models.Act", b =>
                {
                    b.Navigation("ClubNightActs");
                });

            modelBuilder.Entity("WasThere.Api.Models.ClubNight", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClubNightActs");
                });

            modelBuilder.Entity("WasThere.Api.Models.Event", b =>
                {
                    b.Navigation("ClubNights");
                });

            modelBuilder.Entity("WasThere.Api.Models.Flyer", b =>
                {
                    b.Navigation("ClubNights");
                });

            modelBuilder.Entity("WasThere.Api.Models.User", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("WasThere.Api.Models.Venue", b =>
                {
                    b.Navigation("ClubNights");
                });
#pragma warning restore 612, 618
        }
    }
}
